import assert from 'node:assert/strict';
import {buildReportDraft} from '../app/report-draft.mjs';
import {AdaptiveETDRK4} from '../app/etdrk4.mjs';
import {validateRecord} from '../app/storage.mjs';
const solver=new AdaptiveETDRK4({L:16,initialBand:8,stopTime:.01,dt:.001});
const record={schema:'pollen-specimen/2',id:'report-test',title:'My pollen & #1',createdAt:'2026-09-15T00:00:00Z',state:solver.state(),view:{angle:.2,tilt:.3,zoom:1,relief:.1},previewPng:'data:image/png;base64,AA==',observation:'保存時の観察',reference:{id:'test-taxon',species:'Test species',publicationUrl:'https://www.paldat.org/pub/test',imageUrl:'https://www.paldat.org/image/test',requiredCredit:'Photo: test / PalDat',license:'separate'}};
record.view.futureDisplaySetting={sharpness:2,valleyDepth:.5};
const before=JSON.stringify(record);
const similar='似たところ & # = + 日本語\n網目',different='違い'.repeat(5000);
const d=buildReportDraft(record,{similarities:similar,differences:different});
assert.equal(JSON.stringify(record),before);
assert.deepEqual(JSON.parse(d.files.json.text),record);
validateRecord(JSON.parse(d.files.json.text));
assert.equal(d.files.png.dataUrl,record.previewPng);
assert.match(d.files.json.filename,/\.json$/);
assert.match(d.files.png.filename,/\.png$/);
assert.ok(d.fullBody.includes(similar)&&d.fullBody.includes(different));
assert.ok(d.fullBody.includes(record.state.model));
assert.ok(d.fullBody.includes(record.reference.species));
assert.ok(!d.issueUrl.includes('base64'));
const url=new URL(d.issueUrl);
assert.equal(url.origin,'https://github.com');
assert.equal(url.pathname,'/gyroid-eth/pollenarium/issues/new');
assert.equal(url.searchParams.get('title'),d.title);
assert.equal(url.searchParams.get('body')||'',d.issuePrefillBody||'');
assert.ok(d.issueUrl.length<8000,'URL must stay bounded with long observations');
const legacy=structuredClone(record);delete legacy.reference;
const old=buildReportDraft(legacy);
validateRecord(JSON.parse(old.files.json.text));
assert.equal(old.files.png.dataUrl,legacy.previewPng);
console.log('PASS report: saved-state fidelity, immutable input, long text, bounded URL, generated PNG, legacy records');
