import assert from'node:assert/strict';import fs from'node:fs';
import{PROFILE_HEIGHT_MAPPING,LEGACY_HEIGHT_MAPPING,PROFILE_DEFAULTS,resolveHeightView,validateHeightView,renderingDescription,wallProfile,meshAdjacency,normalizeComponents,profileRadii}from'../app/wall-profile.mjs';
import{SpecimenRenderer,radiusForField}from'../app/renderer.mjs';import{SphereBasis}from'../app/spectral.mjs';import{validateRecord}from'../app/storage.mjs';import{buildReportDraft}from'../app/report-draft.mjs';
const saved=JSON.parse(fs.readFileSync(new URL('../assets/equilibrium-presets.json',import.meta.url))).presets[3].state,snapshot=JSON.stringify(saved);
const field=Float64Array.from([-1,-3,1,-2,-4,2]),adj=meshAdjacency(Uint16Array.from([0,1,2,3,4,5]),6),p=normalizeComponents(field,adj);assert.equal(p.components.length,2);
for(const width of[.12,.48,.95])for(const round of[0,.04,1])for(const height of[0,.06,.28]){const v=resolveHeightView({heightMappingVersion:PROFILE_HEIGHT_MAPPING,relief:height,wallWidth:width,tipRoundness:round,wallValley:.08});const r=profileRadii(p.normalized,v);assert.equal(r[1],.78+height);assert.equal(r[4],.78+height);assert.equal(r[5],.78-.08);assert(r.every(Number.isFinite));assert(Math.abs(wallProfile(.88-.72*width,width,round)-.5)<1e-12);let prior=0;for(let i=0;i<=100;i++){const x=wallProfile(i/100,width,round);assert(x>=prior);prior=x}}
for(const f of[Float64Array.of(0,0,0),Float64Array.of(1,1,1),Float64Array.of(-1,-1,-1)])assert(profileRadii(normalizeComponents(f,meshAdjacency(Uint16Array.of(0,1,2),3)).normalized,resolveHeightView()).every(Number.isFinite));
const gl={UNSIGNED_INT:5125,UNSIGNED_SHORT:5123,getExtension:()=>true,bindBuffer(){},bufferData(){}};
const renderer=Object.create(SpecimenRenderer.prototype);Object.assign(renderer,{gl,view:resolveHeightView({heightMappingVersion:PROFILE_HEIGHT_MAPPING,relief:.28}),buffers:{},draw(){}});
const b=new SphereBasis(32),coeff=new Float64Array(b.size);coeff.set(saved.coefficients);const original=b.synthesize(coeff),grid={np:b.np,nt:b.nt,x:b.x};
for(const resolution of[64,96]){renderer.view.wallResolution=resolution;renderer.update(original,grid,saved);assert.equal(renderer.profile.components.length,32);assert.equal(renderer.grid.nt,2*resolution+2);assert(Math.abs(Math.max(...renderer.radii)-1.06)<1e-12);for(let i=0;i<renderer.normals.length;i+=3){assert(Math.abs(Math.hypot(...renderer.normals.subarray(i,i+3))-1)<1e-6);assert(renderer.points.subarray(i,i+3).every(Number.isFinite))}}
const shapedView=renderer.getView(),record={schema:'pollen-specimen/2',id:'wall-test',title:'Wall',createdAt:'2026-09-15',state:saved,view:shapedView,rendering:renderingDescription(shapedView),previewPng:'data:image/png;base64,AA=='};assert.equal(validateRecord(record),record);const imported=JSON.parse(JSON.stringify(record));renderer.restoreView(resolveHeightView(imported.view,imported.rendering));assert.deepEqual(renderer.getView(),shapedView);assert.equal(JSON.stringify(saved),snapshot);
const report=buildReportDraft(record);assert(report.fullBody.includes(PROFILE_HEIGHT_MAPPING));assert.deepEqual(JSON.parse(report.files.json.text),record);assert.equal(report.files.png.dataUrl,record.previewPng);
const missing=resolveHeightView({angle:0,tilt:0,zoom:1,relief:.1,heightMappingVersion:PROFILE_HEIGHT_MAPPING});for(const[k,v]of Object.entries(PROFILE_DEFAULTS))assert.equal(missing[k],v);
renderer.restoreView({angle:.1,tilt:.2,zoom:1,relief:.12});assert.equal(renderer.view.heightMappingVersion,LEGACY_HEIGHT_MAPPING);assert.equal(renderer.view.peakSharpness,1);assert.equal(renderer.view.valleyDepth,1);assert.equal(renderer.profile,null);assert.equal(renderer.grid.np,grid.np);for(let i=0;i<renderer.values.length;i++){const r=radiusForField(renderer.values[i],renderer.view);for(let j=0;j<3;j++)assert.equal(renderer.points[3*i+j],Math.fround(r*renderer.vertices[3*i+j]))}
const legacy={...record,view:{angle:0,tilt:0,zoom:1,relief:.1}};delete legacy.rendering;assert.equal(validateRecord(legacy),legacy);
assert.throws(()=>validateHeightView({...shapedView,wallWidth:0}));assert.throws(()=>validateHeightView({...shapedView,heightMappingVersion:'unknown'}));assert.throws(()=>validateHeightView(shapedView,{heightMapping:{version:LEGACY_HEIGHT_MAPPING}}));assert.throws(()=>validateHeightView(shapedView,{heightMapping:{version:PROFILE_HEIGHT_MAPPING,wallWidth:.9}}));
console.log('PASS component heights, calibrated half-height, uniform fields, two display resolutions, normals, unchanged state, legacy exact geometry, missing-key defaults, JSON/report fidelity and version validation');
