import{SphereBasis,index,seededRandom}from'./spectral.mjs';
export const EQUILIBRIUM_ID='radja-eq6-restricted-real-harmonics-v1';
export const EQ_DEFAULTS={l0:3.5,u:0,r:-1,seed:19,restarts:6,maxIterations:350,tolerance:1e-7};
export function validateEquilibrium(input){const p={...EQ_DEFAULTS,...input};for(let k of Object.keys(EQ_DEFAULTS))if(!Number.isFinite(p[k]))throw Error('Invalid equilibrium parameter '+k);if(p.l0<1||p.l0>24||p.u<-3||p.u>3||p.r<-3||p.r>3)throw Error('Outside supported equilibrium range');if(!Number.isInteger(p.seed)||p.seed<0||p.seed>4294967295||!Number.isInteger(p.restarts)||p.restarts<1||p.restarts>64||p.maxIterations<1||p.maxIterations>3000||p.tolerance<=0)throw Error('Invalid search settings');return p}
const dot=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0),norm=a=>Math.sqrt(dot(a,a));
export class EquilibriumProblem{
 constructor(input={}){this.p=validateEquilibrium(input);let L=Math.ceil(this.p.l0);this.basis=new SphereBasis(L);this.active=[];this.linear=[];const degrees=Number.isInteger(this.p.l0)?[this.p.l0]:[Math.floor(this.p.l0),Math.ceil(this.p.l0)];for(let l of degrees)for(let m=-l;m<=l;m++){this.active.push(index(l,m));this.linear.push((l-this.p.l0)**2+this.p.r)}this.degrees=degrees;this.full=new Float64Array(this.basis.size);this.phi=new Float64Array(this.basis.points);this.nonlinear=new Float64Array(this.basis.points);this.hat=new Float64Array(this.basis.size)}
 evaluate(x){this.full.fill(0);for(let i=0;i<x.length;i++)this.full[this.active[i]]=x[i];const f=this.basis.synthesize(this.full,this.phi),b=this.basis,u=this.p.u;let energy=0;for(let i=0;i<x.length;i++)energy+=.5*this.linear[i]*x[i]*x[i];for(let i=0;i<b.nt;i++){let sum=0;for(let j=0;j<b.np;j++){let k=i*b.np+j,v=f[k];sum+=u/6*v*v*v+v*v*v*v/24;this.nonlinear[k]=u/2*v*v+v*v*v/6}energy+=sum*b.weights[i]*2*Math.PI/b.np}b.analyze(this.nonlinear,this.hat);const gradient=Float64Array.from(x,(v,i)=>this.linear[i]*v+this.hat[this.active[i]]);return{energy,gradient}}
 coefficients(x){const a=new Float64Array(this.basis.size);for(let i=0;i<x.length;i++)a[this.active[i]]=x[i];return a}
}
// Original limited-memory BFGS + Armijo line search, with independently seeded starts.
export class EquilibriumSearch{
 constructor(input={}){this.p=validateEquilibrium(input);this.problem=new EquilibriumProblem(this.p);this.random=seededRandom(this.p.seed);this.restart=0;this.totalIterations=0;this.results=[];this.best=null;this.history=[];this.done=false;this.begin()}
 begin(){const n=this.problem.active.length;this.x=Float64Array.from({length:n},()=>this.random()*2-1);let amplitude=Math.sqrt(4*Math.PI)*1.3/norm(this.x);for(let i=0;i<n;i++)this.x[i]*=amplitude;this.value=this.problem.evaluate(this.x);this.memory=[];this.iteration=0}
 finish(reason){const result={energy:this.value.energy,gradientNorm:norm(this.value.gradient),iterations:this.iteration,reason};this.results.push(result);if(!this.best||result.energy<this.best.energy)this.best={...result,x:this.x.slice(),restart:this.restart};this.restart++;if(this.restart>=this.p.restarts)this.done=true;else this.begin()}
 step(){if(this.done)return false;const g=this.value.gradient;if(norm(g)<this.p.tolerance||this.iteration>=this.p.maxIterations){this.finish(norm(g)<this.p.tolerance?'stationary':'iteration-limit');return true}let q=g.slice(),alphas=[];for(let i=this.memory.length-1;i>=0;i--){const h=this.memory[i],a=h.rho*dot(h.s,q);alphas[i]=a;for(let j=0;j<q.length;j++)q[j]-=a*h.y[j]}if(this.memory.length){const h=this.memory.at(-1),scale=dot(h.s,h.y)/dot(h.y,h.y);for(let j=0;j<q.length;j++)q[j]*=scale}for(let i=0;i<this.memory.length;i++){const h=this.memory[i],beta=h.rho*dot(h.y,q);for(let j=0;j<q.length;j++)q[j]+=h.s[j]*(alphas[i]-beta)}for(let j=0;j<q.length;j++)q[j]=-q[j];let slope=dot(g,q);if(slope>=0){q=Float64Array.from(g,x=>-x);slope=-dot(g,g);this.memory=[]}let step=1,candidate,value;
  for(let j=0;j<30;j++){candidate=Float64Array.from(this.x,(x,i)=>x+step*q[i]);value=this.problem.evaluate(candidate);if(Number.isFinite(value.energy)&&value.energy<=this.value.energy+1e-4*step*slope)break;step*=.5}
  if(!Number.isFinite(value.energy)||value.energy>this.value.energy+1e-10){this.finish('line-search-stalled');return true}const s=Float64Array.from(candidate,(x,i)=>x-this.x[i]),y=Float64Array.from(value.gradient,(x,i)=>x-g[i]),sy=dot(s,y);if(sy>1e-12){this.memory.push({s,y,rho:1/sy});if(this.memory.length>8)this.memory.shift()}this.x=candidate;this.value=value;this.iteration++;this.totalIterations++;if(this.iteration%20===0)this.history.push({restart:this.restart,iteration:this.iteration,energy:value.energy});return true;
 }
 state(){let cur=this.best&&this.best.energy<this.value.energy?this.best:{...this.value,x:this.x,gradientNorm:norm(this.value.gradient),restart:this.restart};const coefficients=this.problem.coefficients(cur.x),b=this.problem.basis;return{model:EQUILIBRIUM_ID,parameters:{...this.p,L:b.L},coefficients:Array.from(coefficients),search:{completedRestarts:this.restart,totalIterations:this.totalIterations,done:this.done,results:this.results.slice(),bestRestart:cur.restart,algorithm:'independent multistart L-BFGS; not an author SA trajectory'},history:this.history.slice(),diagnostics:{energy:cur.energy,gradientNorm:cur.gradientNorm??norm(cur.gradient),degrees:this.problem.degrees,mean:0,quadraturePoints:b.points,stationary:(cur.gradientNorm??norm(cur.gradient))<1e-5,globalMinimumEstablished:false}}}
}
export function minimize(input){const s=new EquilibriumSearch(input);while(!s.done)s.step();return s.state()}
