// Independent implementation of the Cox–Matthews exponential RK4 formula.
// Coefficients use real phi-function series/recurrences, not copied MATLAB code.
// Reference: Kassam & Trefethen (2005), doi:10.1137/S1064827502410633.
import {Simulation} from './spectral.mjs';
export function phi(z,k){if(Math.abs(z)<.7){let factorial=1;for(let i=2;i<=k;i++)factorial*=i;let term=1/factorial,sum=term;for(let j=1;j<60;j++){term*=z/(k+j);sum+=term;if(Math.abs(term)<Math.abs(sum)*1e-17)break}return sum}let value=Math.expm1(z)/z;if(k===1)return value;for(let i=1,f=1;i<k;i++){value=(value-1/f)/z;f*=i+1}return value}
export const ETDRK4_ID='radja-eq7-spherical-etdrk4-v2';
export class ETDRK4 extends Simulation{
 constructor(parameters={},state=null){super(parameters,state);const n=this.a.length;this.stages=Array.from({length:3},()=>new Float64Array(n));this.rhsStages=Array.from({length:4},()=>new Float64Array(n));this.lastCoefficientDt=NaN;this.scheme='cox-matthews-etdrk4-real-phi-v1'}
 coefficientsForStep(h){if(h===this.lastCoefficientDt)return;this.lastCoefficientDt=h;this.weights=Array.from({length:6},()=>new Float64Array(this.a.length));const[E,E2,Q,F1,F2,F3]=this.weights;for(let i=0;i<this.a.length;i++){const z=-h*this.p.D*this.k2[i]*this.alpha[i],p1=phi(z,1),p2=phi(z,2),p3=phi(z,3);E[i]=Math.exp(z);E2[i]=Math.exp(z/2);Q[i]=h/2*phi(z/2,1);F1[i]=h*(p1-3*p2+4*p3);F2[i]=h*(p2-2*p3);F3[i]=h*(-p2+4*p3)}}
 rhs(a,out){this.basis.synthesize(a,this.nonlinear);for(let i=0;i<this.nonlinear.length;i++){const x=this.nonlinear[i];this.nonlinear[i]=this.p.u3/2*x*x+this.p.u4/6*x*x*x}this.basis.analyze(this.nonlinear,out);for(let i=0;i<out.length;i++)out[i]*=-this.p.D*this.k2[i]}
 step(until=this.p.stopTime){if(this.time>=until-1e-12)return false;const h=Math.min(this.p.dt,until-this.time);this.coefficientsForStep(h);const[E,E2,Q,F1,F2,F3]=this.weights,[A,B,C]=this.stages,[N0,NA,NB,NC]=this.rhsStages,n=this.a.length;this.rhs(this.a,N0);for(let i=0;i<n;i++)A[i]=E2[i]*this.a[i]+Q[i]*N0[i];this.rhs(A,NA);for(let i=0;i<n;i++)B[i]=E2[i]*this.a[i]+Q[i]*NA[i];this.rhs(B,NB);for(let i=0;i<n;i++)C[i]=E2[i]*A[i]+Q[i]*(2*NB[i]-N0[i]);this.rhs(C,NC);for(let i=0;i<n;i++)this.candidate[i]=E[i]*this.a[i]+F1[i]*N0[i]+2*F2[i]*(NA[i]+NB[i])+F3[i]*NC[i];this.candidate[0]=this.a[0];this.basis.synthesize(this.candidate,this.candidateField);const energy=this.computeEnergy(this.candidate,this.candidateField);if(!Number.isFinite(energy)||!this.candidate.every(Number.isFinite))throw Error('ETDRK4 nonfinite state; reduce timestep');if(energy>this.energy+1e-7*Math.max(1,Math.abs(this.energy)))throw Error(`ETDRK4 energy increase at t=${this.time}; reduce timestep`);[this.a,this.candidate]=[this.candidate,this.a];[this.field,this.candidateField]=[this.candidateField,this.field];this.energy=energy;this.time+=h;this.steps++;this.lastDt=h;this.nextDt=this.p.dt;if(this.steps%10===0||this.time>=until-1e-12)this.history.push({time:this.time,energy:this.energy});return true}
 state(){return{...super.state(),model:ETDRK4_ID,scheme:this.scheme}}
}
export function morphology(s){const p=s.basis.power(s.a),total=p.slice(1).reduce((a,b)=>a+b,0),mean=s.a[0]/Math.sqrt(4*Math.PI),rms=Math.sqrt(total/(4*Math.PI));let lMean=0,l2=0,positive=0,m3=0,m4=0;for(let l=1;l<p.length;l++){lMean+=l*p[l];l2+=l*l*p[l]}lMean/=Math.max(total,1e-30);l2/=Math.max(total,1e-30);const b=s.basis;for(let i=0;i<b.nt;i++)for(let j=0;j<b.np;j++){const x=s.field[i*b.np+j]-mean,w=b.weights[i]/(2*b.np);positive+=(x>0?w:0);m3+=w*x**3;m4+=w*x**4}return{...s.diagnostics(),rms,meanDegree:lMean,degreeSpread:Math.sqrt(Math.max(0,l2-lMean*lMean)),positiveAreaFraction:positive,skewness:m3/Math.max(rms**3,1e-30),kurtosis:m4/Math.max(rms**4,1e-30)}}
export function compare(a,b){const n=Math.max(a.length,b.length);let e=0,aa=0,bb=0,ab=0;for(let i=0;i<n;i++){const x=a[i]||0,y=b[i]||0;e+=(x-y)**2;aa+=x*x;bb+=y*y;ab+=x*y}return{relativeL2:Math.sqrt(e/Math.max(bb,1e-30)),correlation:ab/Math.sqrt(Math.max(aa*bb,1e-30))}}

// Browser integration: reject failed/energy-increasing steps, preserve nextDt for continuation.
// Acceptance is a stability check, not a substitute for timestep refinement.
export class AdaptiveETDRK4 extends ETDRK4{
 step(until=this.p.stopTime){if(this.time>=until-1e-12)return false;const upper=this.p.dt;let h=Math.min(this.nextDt,upper,until-this.time),lastError;for(let attempt=0;attempt<18;attempt++){this.p.dt=h;try{const advanced=super.step(until);this.p.dt=upper;this.nextDt=Math.min(upper,h*1.05);return advanced}catch(e){this.p.dt=upper;lastError=e;h*=.5;this.rejected++}}throw Error('ETDRK4 could not accept a finite energy-decreasing step: '+lastError?.message)}
 state(){return{...super.state(),timeStepping:'ETDRK4 with energy-rejection halving; stored nextDt',resumeVersion:2}}
}
