import{createTaxonNames}from'./taxon-names.mjs';
import{ReferenceAtlas,paperPresetLabel,wikipediaLabel}from'./atlas.mjs';
import{buildReportDraft}from'./report-draft.mjs';
import{DEFAULTS,MODEL_ID,validateParameters}from'./spectral.mjs';
import{EQ_DEFAULTS,EQUILIBRIUM_ID,validateEquilibrium}from'./equilibrium.mjs';
import{DEFAULT_HEIGHT_VIEW,HEIGHT_MAPPING_VERSION,SpecimenRenderer}from'./renderer.mjs';
import{listRecords,putRecord,validateRecord,downloadRecord}from'./storage.mjs';
const $=id=>document.getElementById(id),worker=new Worker(new URL('./worker.mjs',import.meta.url),{type:'module'});
let renderer,mode='equilibrium',draft={...EQ_DEFAULTS},current=null,job=0,busy=false,dirty=false,origin='独自に計算した論文条件プリセット',references,presets,computed,currentReference,records=[];
let taxonName=species=>({full:species,label:'',group:'',name:null});
const fmt=(x,n=3)=>Number.isFinite(x)?Number(x).toPrecision(n):'—';
let toastTimer;function toast(message){$('toast').textContent=message;$('toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').style.display='none',4500)}
function failure(e){$('status').textContent='計算を確認してください';$('status').classList.add('error');toast(e.message||String(e));busy=false;buttons()}
const eqControls=[['l0','模様の細かさ · l₀',1,24,.1,'整数なら1次数、その間は隣接2次数を使います。'],['u','山と谷の非対称性 · u',-3,3,.05,'符号を変えると突出とくぼみの関係が入れ替わります。'],['r','秩序化の強さ · r',-3,3,.05,'論文の相図は −1。自由探索では変更できます。']];
const dynControls=[['q0','模様の細かさ · q₀',.2,2.5,.05,'大きいほど細かな模様を好む傾向。選択波長そのものではありません。'],['tau','相分離への傾き · τ',-25,25,.5,'負側で一様な状態から模様が育ちやすくなります。'],['u3','山と谷の非対称性 · u₃',-60,60,1,'三次項。符号を変えると模様の反転に関わります。'],['stopTime','育てる時間 · t',0,60,.5,'無次元の計算時間。生物の実時間ではありません。']];
const eqAdvanced=[['seed','初期乱数 · seed',0,4294967295,1,'同じ条件とseedで同じ探索を再実行。'],['restarts','探索する初期配置の数',1,64,1,'複数の候補から最も低いエネルギーを残します。'],['maxIterations','各探索の反復上限',50,3000,50,'途中終了も記録に残ります。']];
const dynAdvanced=[['seed','初期乱数 · seed',0,4294967295,1,'同じ帯域の初期場を再現。'],['noise','初期ゆらぎ · RMS',0,.4,.01,'保持した次数のRMS。原著のセルごとの標準偏差とは異なります。'],['initialBand','初期雑音の最大次数',1,96,1,'セルごとの白色雑音ではなく帯域制限した雑音。'],['mean','保存される平均場',-.5,.5,.01,'計算中はこの平均を保存します。'],['R','球の半径 · R',5,30,1,'論文条件は15。q₀と併せて球面上の模様数に関与。'],['dt','時間刻みの上限 · Δt',.0001,.05,.0001,'エネルギーが増えると自動的に縮小します。']];
function controls(){
 for(let [id,defs]of[['basic-controls',mode==='equilibrium'?eqControls:dynControls],['advanced-controls',mode==='equilibrium'?eqAdvanced:dynAdvanced]]){
  $(id).replaceChildren();for(const[key,label,min,max,step,hint]of defs){const div=document.createElement('div');div.className='control';const row=document.createElement('div');row.className='control-top';const lab=document.createElement('label');lab.htmlFor=`p-${key}`;lab.textContent=label;const num=document.createElement('input');num.id=`p-${key}`;num.type='number';Object.assign(num,{min,max,step,value:draft[key]});row.append(lab,num);div.append(row);
   if(id==='basic-controls'){const range=document.createElement('input');range.type='range';range.setAttribute('aria-label',label);Object.assign(range,{min,max,step,value:draft[key]});range.oninput=()=>{num.value=range.value;change(key,Number(range.value))};num.oninput=()=>{range.value=num.value;change(key,Number(num.value))};div.append(range)}else num.oninput=()=>change(key,Number(num.value));
   const small=document.createElement('small');small.textContent=hint;div.append(small);$(id).append(div)}
 }
 if(mode==='dynamics'){const label=document.createElement('label');label.className='control';label.textContent='空間解像度 · 最大次数 L ';const select=document.createElement('select');select.id='p-L';for(let L of[16,24,32,48,64,96])select.add(new Option(String(L),L));select.value=draft.L;select.onchange=()=>change('L',Number(select.value));label.append(select);$('advanced-controls').append(label);const p=document.createElement('p');p.className='hint';p.textContent='D=K=1、u₄=120 を固定。保存JSONには定数も記録します。';$('advanced-controls').append(p)}
 $('mode-description').textContent=mode==='equilibrium'?'エネルギーの低い形を探す。大きな突起、くぼみ、螺旋を見比べよう。':'球面上で模様が変わる過程を観察。気になる瞬間で止めてみよう。';
 $('run').textContent=mode==='equilibrium'?'この条件で探索する ↗':'この条件で育てる ↗';
 $('model-tag').textContent=mode==='equilibrium'?'EQ. 6 / 平衡探索':'EQ. 7 / 保存的な時間発展';
 for(let k of['equilibrium','dynamics'])$('mode-'+k).classList.toggle('selected',mode===k);
}
function change(key,value){draft[key]=value;dirty=true;$('preset').value='custom';buttons()}
function buttons(){ $('run').disabled=busy;$('pause').disabled=!busy;$('save').disabled=busy||!current||dirty;$('continue').hidden=mode!=='dynamics'||!current||busy||dirty;$('draft-note').textContent=dirty?'条件を変更しました。再計算してから標本に残せます。':busy?'計算中。停止すると、今の状態を標本に残せます。':'条件・計算場・表示・観察メモを一緒に保存。';}
function presetMenu(){
 const select=$('preset');select.replaceChildren(new Option('自由に条件を設定','custom'));
 const entries=(mode==='equilibrium'?presets.equilibrium:presets.dynamics).map((p,i)=>({p,i}));
 if(mode==='equilibrium')entries.sort((a,b)=>a.p.species.localeCompare(b.p.species,'en'));
 // Keep source indices as option values: precomputed states follow Table 1 order.
 for(const {p,i} of entries)select.add(new Option(mode==='equilibrium'?`${taxonName(p.species).full} · l₀ ${p.l0} / u ${p.u}`:`${p.name} · q₀ ${p.q0} / τ ${p.tau}`,String(i)));
}
function metric(name,value){const div=document.createElement('div');div.className='metric';const s=document.createElement('small');s.textContent=name;const b=document.createElement('strong');b.textContent=value;div.append(s,b);return div}
function showState(m){current=m.state;if(mode==='dynamics')$('model-tag').textContent=current.model===MODEL_ID?'EQ. 7 / 旧方式の標本':'EQ. 7 / 4次時間積分';renderer.update(m.field,m.grid,current);const d=current.diagnostics;
 $('metrics').replaceChildren(...(mode==='equilibrium'?[metric('ENERGY',fmt(d.energy,5)),metric('GRADIENT',fmt(d.gradientNorm,2)),metric('STARTS',`${current.search?.completedRestarts??'—'} / ${current.parameters.restarts}`)]:[metric('TIME',fmt(current.time,4)),metric('MEAN DRIFT',fmt(d.meanDrift,2)),metric('PEAK DEGREE',String(d.peakDegree))]));
 $('result-note').textContent=mode==='equilibrium'?`${origin}。停留点候補 / 大域最小は未保証。`:`${origin}。高次数側のパワー ${(d.tailPowerFraction*100).toFixed(2)}%${d.tailPowerFraction>.01?' — 解像度を上げた比較が必要です。':'。'} 刻み・解像度の収束は条件ごとに確認が必要です。`;
 if(m.type==='done'||m.type==='paused'||m.type==='restored'){busy=false;$('status').textContent=m.type==='done'?'計算完了':m.type==='paused'?'停止して観察中':'標本を表示中'}else $('status').textContent=mode==='equilibrium'?`探索 ${current.search.completedRestarts+1}/${draft.restarts}`:`t = ${current.time.toFixed(2)}`;
 buttons();
}
worker.onmessage=({data:m})=>{if(m.job!==job)return;if(m.type==='error'){failure(Error(m.message));return}try{showState(m)}catch(e){failure(e)}};worker.onerror=e=>failure(Error(e.message||'Worker error'));
function send(type,parameters,state=null){job++;busy=type==='run';dirty=false;current=null;$('status').classList.remove('error');worker.postMessage({type,mode,job,parameters,state});buttons()}
function loadPreset(i){if(i==='custom')return;const p=(mode==='equilibrium'?presets.equilibrium:presets.dynamics)[Number(i)];if(mode==='equilibrium'){const s=computed.presets[Number(i)].state;draft={...s.parameters};origin=`Table 1 · ${p.species} / 独自の事前計算`;controls();send('restore',draft,s)}else{worker.postMessage({type:'pause',job});job++;busy=false;draft={...DEFAULTS,...p,u3:-40,u4:120,K:1,D:1,R:15,noise:.2,initialBand:32,L:96,dt:.00125,stopTime:2};origin=`${p.name} の係数 / 独自の初期場`;controls();current=null;dirty=true;buttons();$('status').textContent='条件を読み込みました';$('metrics').replaceChildren();$('result-note').textContent='「育てる」で新しい条件を計算します。球体は直前の結果です。'} }
function switchMode(next){worker.postMessage({type:'pause',job});job++;busy=false;current=null;mode=next;draft=mode==='equilibrium'?{...EQ_DEFAULTS}:{...DEFAULTS};origin='ブラウザで独自に計算';controls();presetMenu();if(mode==='equilibrium'){$('preset').value='25';loadPreset('25')}else{renderer.setView({relief:.18});syncViewControls();send('run',draft)}}
function updateReference(id,stored=null){const ref=references.images.find(x=>x.id===id)||stored||(currentReference?.id===id?currentReference:null)||references.images[0];currentReference=ref;if(stored&&!references.images.some(x=>x.id===ref.id))references.images.push(ref);if(![...$('reference').options].some(o=>o.value===ref.id))$('reference').add(new Option(taxonName(ref.species).full,ref.id));$('reference').value=ref.id;$('species').textContent=ref.species;const names=taxonName(ref.species);$('species-ja').textContent=names.label;$('species-group').textContent=names.name?names.group:'';$('species-group').hidden=!names.name;$('name-source').hidden=!names.label;const accepted=ref.taxonomy?.acceptedScientificName;$('species-taxonomy').textContent=accepted&&ref.taxonomy?.inputStatus==='synonym'?`現行の受理名：${accepted}`:'';$('species-taxonomy').hidden=!$('species-taxonomy').textContent;const matched=paperPresetLabel(ref);$('paper-match').textContent=matched?`${matched}。分類名の対応であり、この写真への形態フィットではありません。`:'';$('paper-match').hidden=!matched;const wiki=ref.wikipedia;$('wikipedia').hidden=!wiki;if(wiki){$('wikipedia').href=wiki.url;$('wikipedia').textContent=wikipediaLabel(ref)}$('sem').alt=`${ref.species}のSEM写真。${ref.requiredCredit}`;if(ref.localPath)$('sem').src=new URL('../'+ref.localPath,import.meta.url);$('sem').hidden=!ref.localPath;$('media-missing').hidden=!!ref.localPath;$('sem').onerror=()=>{$('sem').hidden=true;$('media-missing').hidden=false};$('source').href=ref.publicationUrl;$('missing-link').href=ref.publicationUrl;$('credit').textContent=ref.requiredCredit;$('focus').textContent=ref.observationHintJa||'保存された参照標本。詳しい観察情報は出典をご覧ください。'}
async function save(){if(busy||dirty||!current)return;const ref=currentReference,view=renderer.getView(),record={schema:'pollen-specimen/2',id:crypto.randomUUID(),createdAt:new Date().toISOString(),title:$('title').value.trim()||`${mode==='equilibrium'?'平衡のかたち':'模様の成長'} · ${new Date().toLocaleDateString('ja-JP')}`,observation:$('observation').value,origin,state:structuredClone(current),view,previewPng:renderer.png(),reference:{id:ref.id,species:ref.species,paldatSpecies:ref.paldatSpecies||ref.species,publicationUrl:ref.publicationUrl,imageUrl:ref.imageUrl,requiredCredit:ref.requiredCredit,license:ref.license,taxonomy:ref.taxonomy||null,wikipedia:ref.wikipedia||null,paperPreset:ref.paperPreset||null},rendering:{version:'scalar-monotone-height-v2',heightMapping:{version:HEIGHT_MAPPING_VERSION,baseRadius:.78,relief:view.relief,peakSharpness:view.peakSharpness,valleyDepth:view.valleyDepth},meaning:'geometric scalar-field height display, not deposition, growth, or wall-thickness physics'}};validateRecord(record);await putRecord(record);await cabinet();toast('標本箱に保存しました。JSONで持ち出せます。')}
let reportRecord=null,reportDraft=null,reportTimer;
function downloadBlob(content,type,filename){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function downloadDataUrl(dataUrl,filename){const a=document.createElement('a');a.href=dataUrl;a.download=filename;a.click()}
function refreshReport(){if(!reportRecord)return;reportDraft=buildReportDraft(reportRecord,{similarities:$('report-similarities').value,differences:$('report-differences').value});$('report-body').value=reportDraft.fullBody;$('report-github').href=reportDraft.issueUrl}
function scheduleReport(){clearTimeout(reportTimer);reportTimer=setTimeout(refreshReport,120)}
function openReport(record){reportRecord=record;$('report-similarities').value='';$('report-differences').value='';$('report-context').textContent=`${record.title} · ${record.reference?.species||'観察標本なし'} · ${record.state.model}`;refreshReport();$('report-dialog').showModal();$('report-similarities').focus({preventScroll:true})}
async function copyReport(){refreshReport();try{await navigator.clipboard.writeText(reportDraft.fullBody)}catch{$('report-body').focus();$('report-body').select();if(!document.execCommand('copy'))throw Error('本文を選択しました。コピー操作をしてください')}toast('完全な本文をコピーしました')}
function syncViewControls(){const view=renderer.getView();$('relief').value=view.relief;$('peak-sharpness').value=view.peakSharpness;$('valley-depth').value=view.valleyDepth;$('peak-sharpness-value').value=view.peakSharpness.toFixed(2);$('valley-depth-value').value=view.valleyDepth.toFixed(2)}
function setHeightView(key,value){renderer.setView({[key]:value});syncViewControls()}
function restore(record){validateRecord(record);mode=record.state.model===EQUILIBRIUM_ID?'equilibrium':'dynamics';draft={...record.state.parameters};origin='保存した標本を復元';controls();presetMenu();$('preset').value='custom';$('title').value=record.title;$('observation').value=record.observation||'';renderer.restoreView(record.view);syncViewControls();updateReference(record.reference?.id,record.reference);send('restore',draft,record.state);$('specimen').scrollIntoView({block:'center',behavior:'smooth'});toast(mode==='equilibrium'?'形と条件を復元しました。探索は改めて実行できます。':'全係数と保存時刻を復元しました。数値計算を続行できます。')}
async function cabinet(){records=await listRecords();$('count').textContent=records.length;$('records').replaceChildren();if(!records.length){const p=document.createElement('div');p.className='empty';p.textContent='最初の標本は、ちょっと気になった形でいい。条件を変えて、ここに並べてみよう。';$('records').append(p)}for(let r of records){const card=document.createElement('article');card.className='card';const img=document.createElement('img');img.src=r.previewPng;img.alt=r.title;const body=document.createElement('div');body.className='card-body';const title=document.createElement('h3');title.textContent=r.title;const info=document.createElement('p'),p=r.state.parameters,eq=r.state.model===EQUILIBRIUM_ID;info.textContent=eq?`Eq. 6 · l₀ ${p.l0} · u ${p.u} · r ${p.r}`:`Eq. 7 · q₀ ${p.q0} · τ ${p.tau} · t ${fmt(r.state.time,4)}`;const date=document.createElement('p');date.textContent=`seed ${p.seed} · ${new Date(r.createdAt).toLocaleDateString('ja-JP')}`;const note=document.createElement('p');note.className='observation-note';note.textContent=r.observation||'';const actions=document.createElement('div');actions.className='card-actions';const open=document.createElement('button');open.className='restore';open.textContent='取り出す';open.onclick=()=>{try{restore(r)}catch(e){failure(e)}};const exp=document.createElement('button');exp.textContent='JSON ↗';exp.onclick=()=>downloadRecord(r);const report=document.createElement('button');report.className='report';report.textContent='この結果を報告';report.onclick=()=>{try{openReport(r)}catch(e){failure(e)}};actions.append(open,exp);body.append(title,info,date,note,actions,report);card.append(img,body);$('records').append(card)}}
$('run').onclick=()=>{try{draft=mode==='equilibrium'?validateEquilibrium(draft):validateParameters(draft);origin='ブラウザで独自に計算';send('run',draft)}catch(e){failure(e)}};
$('pause').onclick=()=>worker.postMessage({type:'pause',job});
$('continue').onclick=()=>{if(mode!=='dynamics'||!current||busy||dirty)return;draft={...current.parameters,stopTime:Math.max(current.parameters.stopTime,current.time+2)};controls();origin='保存した数値状態から続行';send('run',draft,current)};
$('save').onclick=()=>save().catch(failure);$('preset').onchange=e=>loadPreset(e.target.value);$('reference').onchange=e=>updateReference(e.target.value);
for(let m of['equilibrium','dynamics'])$('mode-'+m).onclick=()=>{if(mode!==m)switchMode(m)};
$('relief').oninput=e=>setHeightView('relief',Number(e.target.value));$('peak-sharpness').oninput=e=>setHeightView('peakSharpness',Number(e.target.value));$('valley-depth').oninput=e=>setHeightView('valleyDepth',Number(e.target.value));$('reset-view-shape').onclick=()=>{renderer.setView(DEFAULT_HEIGHT_VIEW);syncViewControls();toast('追加の見せ方を元に戻しました')};
$('import').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>20*1024*1024)throw Error('20 MB 以下の標本JSONを選んでください');const r=validateRecord(JSON.parse(await file.text()));await putRecord({...r,id:crypto.randomUUID(),importedFrom:r.id});await cabinet();toast('標本を読み込みました')}catch(err){failure(err)}finally{e.target.value=''}};
$('about-button').onclick=()=>$('about').showModal();$('close-about').onclick=()=>$('about').close();
$('close-report').onclick=()=>$('report-dialog').close();$('report-similarities').oninput=scheduleReport;$('report-differences').oninput=scheduleReport;$('report-body').onclick=e=>e.currentTarget.select();$('report-copy').onclick=()=>copyReport().catch(failure);$('report-download-json').onclick=()=>{refreshReport();downloadBlob(reportDraft.files.json.text,reportDraft.files.json.mimeType,reportDraft.files.json.filename)};$('report-download-png').onclick=()=>{refreshReport();downloadDataUrl(reportDraft.files.png.dataUrl,reportDraft.files.png.filename)};$('report-github').onclick=refreshReport;
try{renderer=new SpecimenRenderer($('specimen'));renderer.setView({relief:.06});syncViewControls();const loaded=await Promise.all(['../references/paldat-manifest.json','../references/paper-presets.json','../assets/equilibrium-presets.json','../references/japanese-names.json'].map(async path=>{const r=await fetch(new URL(path,import.meta.url));if(!r.ok)throw Error('データを読めません: '+path);return r.json()}));[references,presets,computed]=loaded;taxonName=createTaxonNames(loaded[3]);for(const ref of references.images)$('reference').add(new Option(taxonName(ref.species).full,ref.id));new ReferenceAtlas({images:references.images,taxonName,onSelect:id=>updateReference(id),selectedId:()=>currentReference?.id});updateReference('berberis-vulgaris-303900-1012963');controls();presetMenu();$('preset').value='25';loadPreset('25');await cabinet()}catch(e){failure(e)}
