// A smooth graphical interpretation of a scalar field, not a wall-thickness model.
export class SpecimenRenderer{
 constructor(canvas){this.canvas=canvas;this.gl=canvas.getContext('webgl',{alpha:true,antialias:true,preserveDrawingBuffer:true});if(!this.gl)throw Error('このブラウザではWebGLを使えません');const gl=this.gl;
  const vertex=`attribute vec3 p;attribute vec3 n;attribute float field;uniform mat3 rot;uniform float aspect;varying vec3 norm;varying float f;void main(){vec3 v=rot*p;norm=rot*n;f=field;gl_Position=vec4(v.x/aspect,v.y,-v.z*.3,1.);}`;
  const fragment=`precision mediump float;varying vec3 norm;varying float f;uniform vec3 tint;uniform float contrast;void main(){vec3 n=normalize(norm);vec3 l=normalize(vec3(-.65,.8,1.25));float d=max(dot(n,l),0.);float s=pow(max(dot(reflect(-l,n),vec3(0.,0.,1.)),0.),28.);float rim=pow(1.-max(n.z,0.),3.);float tone=.15+.85/(1.+exp(clamp(f*contrast,-12.,12.)));vec3 col=tint*(.18+.8*d)*tone+vec3(s*.12)+rim*tint*.08;gl_FragColor=vec4(col,1.);}`;
  const compile=(type,source)=>{let s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s};this.program=gl.createProgram();gl.attachShader(this.program,compile(gl.VERTEX_SHADER,vertex));gl.attachShader(this.program,compile(gl.FRAGMENT_SHADER,fragment));gl.linkProgram(this.program);if(!gl.getProgramParameter(this.program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(this.program));gl.useProgram(this.program);this.buffers={};for(const name of ['p','n','field']){let buf=gl.createBuffer();this.buffers[name]=buf;gl.bindBuffer(gl.ARRAY_BUFFER,buf);const loc=gl.getAttribLocation(this.program,name);gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,name==='field'?1:3,gl.FLOAT,false,0,0)}this.indices=gl.createBuffer();gl.enable(gl.DEPTH_TEST);this.view={angle:-.3,tilt:.18,zoom:1,relief:.13,palette:'silver'};let drag=false,px,py;
  canvas.onpointerdown=e=>{drag=true;px=e.clientX;py=e.clientY;canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(!drag)return;this.view.angle+=(e.clientX-px)*.008;this.view.tilt+=(e.clientY-py)*.008;px=e.clientX;py=e.clientY;this.draw()};canvas.onpointerup=()=>drag=false;canvas.onwheel=e=>{e.preventDefault();this.view.zoom=Math.max(.65,Math.min(1.4,this.view.zoom-e.deltaY*.001));this.draw()};this.resize=new ResizeObserver(()=>this.draw());this.resize.observe(canvas);
 }
 createGrid(grid){this.grid=grid;const{np,nt,x}=grid,n=np*nt;this.vertices=new Float64Array((n+2)*3);for(let i=0;i<nt;i++){const z=x[i],r=Math.sqrt(1-z*z);for(let j=0;j<np;j++){const t=2*Math.PI*j/np,k=(i*np+j)*3;this.vertices[k]=r*Math.cos(t);this.vertices[k+1]=z;this.vertices[k+2]=r*Math.sin(t)}}this.vertices[n*3+1]=-1;this.vertices[(n+1)*3+1]=1;let faces=[];for(let i=0;i<nt-1;i++)for(let j=0;j<np;j++){const a=i*np+j,b=i*np+(j+1)%np,c=(i+1)*np+j,d=(i+1)*np+(j+1)%np;faces.push(a,b,c,b,d,c)}for(let j=0;j<np;j++){faces.push(n,(j+1)%np,j);faces.push(n+1,(nt-1)*np+j,(nt-1)*np+(j+1)%np)}this.indexType=(n+2)>65535?this.gl.UNSIGNED_INT:this.gl.UNSIGNED_SHORT;if(this.indexType===this.gl.UNSIGNED_INT&&!this.gl.getExtension('OES_element_index_uint'))throw Error('この端末では高解像度表示を使えません');this.faces=(n+2)>65535?new Uint32Array(faces):new Uint16Array(faces);this.points=new Float32Array(this.vertices.length);this.normals=new Float32Array(this.vertices.length);this.values=new Float32Array(n+2);const gl=this.gl;gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,this.indices);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,this.faces,gl.STATIC_DRAW);
 }
 update(field,grid,state){this.contrast=state.model.includes("eq6")?1.4:4.;if(!this.grid||this.grid.np!==grid.np||this.grid.nt!==grid.nt)this.createGrid(grid);this.values.set(field);let south=0,north=0;for(let l=0;l<=state.parameters.L;l++){const a=state.coefficients[l*l+l]*Math.sqrt((2*l+1)/(4*Math.PI));north+=a;south+=(l%2?-a:a)}this.values[this.values.length-2]=south;this.values[this.values.length-1]=north;this.rebuild()}
 rebuild(){if(!this.vertices)return;const pts=this.points,norm=this.normals,vals=this.values,v=this.vertices;for(let i=0;i<vals.length;i++){const rad=.78-this.view.relief*Math.tanh(vals[i]);for(let k=0;k<3;k++)pts[i*3+k]=v[i*3+k]*rad}norm.fill(0);for(let i=0;i<this.faces.length;i+=3){const a=this.faces[i]*3,b=this.faces[i+1]*3,c=this.faces[i+2]*3,ux=pts[b]-pts[a],uy=pts[b+1]-pts[a+1],uz=pts[b+2]-pts[a+2],vx=pts[c]-pts[a],vy=pts[c+1]-pts[a+1],vz=pts[c+2]-pts[a+2];let nx=uy*vz-uz*vy,ny=uz*vx-ux*vz,nz=ux*vy-uy*vx;if(nx*pts[a]+ny*pts[a+1]+nz*pts[a+2]<0){nx=-nx;ny=-ny;nz=-nz}for(let j of[a,b,c]){norm[j]+=nx;norm[j+1]+=ny;norm[j+2]+=nz}}
  const gl=this.gl;for(let [key,arr]of[['p',pts],['n',norm],['field',vals]]){gl.bindBuffer(gl.ARRAY_BUFFER,this.buffers[key]);gl.bufferData(gl.ARRAY_BUFFER,arr,gl.DYNAMIC_DRAW)}this.draw();
 }
 draw(){if(!this.vertices)return;const gl=this.gl,c=this.canvas,r=c.getBoundingClientRect(),dpr=Math.min(window.devicePixelRatio||1,2),w=Math.round(r.width*dpr),h=Math.round(r.height*dpr);if(!w||!h)return;if(c.width!==w||c.height!==h){c.width=w;c.height=h}gl.viewport(0,0,w,h);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.useProgram(this.program);const {angle,tilt,zoom,palette}=this.view,a=Math.cos(angle),b=Math.sin(angle),u=Math.cos(tilt),v=Math.sin(tilt);gl.uniformMatrix3fv(gl.getUniformLocation(this.program,'rot'),false,new Float32Array([a,v*b,-u*b,0,u,v,b,-v*a,u*a].map(x=>x*zoom)));gl.uniform1f(gl.getUniformLocation(this.program,'aspect'),w/h);gl.uniform1f(gl.getUniformLocation(this.program,'contrast'),this.contrast||1.4);gl.uniform3fv(gl.getUniformLocation(this.program,'tint'),palette==='amber'?[.95,.76,.42]:[.9,.93,.89]);gl.drawElements(gl.TRIANGLES,this.faces.length,this.indexType,0)}
 getView(){return {...this.view}}
 setView(view){this.view={...this.view,...view};this.rebuild()}
 png(){return this.canvas.toDataURL('image/png')}
}
